# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_gurobi <- function(model, param_names, param_vals, NumberSolutions, verbose) {
    .Call('rgurobi_solve_gurobi', PACKAGE = 'rgurobi', model, param_names, param_vals, NumberSolutions, verbose)
}

